
<!-- This is the project specific website template -->
<!-- It can be changed as liked or replaced by other content -->

<?php

$domain=ereg_replace('[^\.]*\.(.*)$','\1',$_SERVER['HTTP_HOST']);
$group_name=ereg_replace('([^\.]*)\..*$','\1',$_SERVER['HTTP_HOST']);
$themeroot='http://r-forge.r-project.org/themes/rforge/';

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en   ">

  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $group_name; ?></title>
	<link href="<?php echo $themeroot; ?>styles/estilo1.css" rel="stylesheet" type="text/css" />
  </head>

<body>

<! --- R-Forge Logo --- >
<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr><td>
<a href="/"><img src="<?php echo $themeroot; ?>/images/logo.png" border="0" alt="R-Forge Logo" /> </a> </td> </tr>
</table>


<!-- get project title  -->
<!-- own website starts here, the following may be changed as you like -->

<?php if ($handle=fopen('http://'.$domain.'/export/projtitl.php?group_name='.$group_name,'r')){
$contents = '';
while (!feof($handle)) {
	$contents .= fread($handle, 8192);
}
fclose($handle);
echo $contents; } ?>

<!-- end of project description -->

<ul>
  <li><big>STAR is an <a href="http://www.r-project.org/">R</a> package
to analyze spike trains. It provides tools to visualize spike trains
and fit, test and compare models of discharge applied to actual data.</big></li>
  <li><big>STAR works with spike train(s) from one neuron or several neurons
simultaneously recorded.<br>
    </big></li>
    <li><big>STAR can perform automatic analysis of spike trains and generate html reports. 
    The following two links show reports generated by a single command of STAR:
    <ul>
  <li><a href="STAR_folder/e070528spontN1.html">In the spontaneous regime</a>. 
  The example of function/method <span style="font-family: monospace;">reportHTML.spikeTrain</span> shows how to generate this report.</li>
  <li><a href="STAR_folder/e070528citronellalN1.html">With repeated stimulations applied</a>.
  The example of function/method <span style="font-family: monospace;">reportHTML.repeatedTrain</span> shows how to generate this report.</li>
  <br>
    </big></li>
 </ul>
 <li><big>STAR runs with the last version of R: R-2.6.0<br>
    </big></li>
    <li><big>A <a href="STAR_folder/PouzatChaffiol_STARdraft.pdf">draft of a manuscript</a> describing the basic functionalities of STAR and including a tutorial is available. Last update: November 13.<br>
    </big></li>
 
 
<br>
<hr style="width: 100%; height: 2px;"><big><span
 style="font-weight: bold;">Features presently implemented in STAR
include</span>:<br>
</big>
<ul>
  <li><big>Instantaneous firing rate estimates. They are obtained with
a convolution of a Gaussian kernel with the spike train.</big></li>
  <li><big>Test of independence of successive inter-spike intervals
(ISIs) in stationary discharge regimes.</big></li>
  <li><big>Fit of an ISI sample from a single neuron in stationary
regime with various models: log-normal, inverse Gaussian, gamma,
Weibull, refractory-exponential, log-logistic. The model parameters are obtained with the
method of maximum likelihood and models are compared with AIC.</big></li>
  <li><big>Test of the adequacy of the best model above.</big></li>
  <li><big>Cross-correlograms of spike trains from different neurons
recorded simultaneously.</big></li>
  <li><big>The time rescaling (<a href="http://www.stat.cmu.edu/~kass/papers/rescaling.pdf" >Brown et al, 2002, Neural Comp. 14: 325</a>) / time transformation (<a href="http://links.jstor.org/sici?sici=0162-1459%28198803%2983%3A401%3C9%3ASMFEOA%3E2.0.CO%3B2-1" >Ogata, 1988, JASA, 83: 9</a>)
is implemented with the full collection of tests of Ogata (1988).
</big></li>
<li><big>The statistical smoothing approach of <a href="http://www.stat.cmu.edu/~kass/papers/smooth.pdf" >Kass, Ventura and Cai (2003) Network: Computation in Neural Systems 14: 5</a>.
But instead of their BARS method a GAM (General Additive Model) based approach with the R package <span style="font-family: monospace;">mgcv</span> of 
Simon Wood is used.
</big></li>
<li><big>The spike-train probability model approach of <a href="http://www.stat.cmu.edu/~kass/papers/imi.pdf"">Kass and Ventura (2001) Neural Comp. 13: 1713</a>.
The job is done again using the GAM based approach of <span style="font-family: monospace;">mgcv</span>.
</big></li>
<li><big>Hidden Markov Models can be used in the spontaneous regime. 
</big></li>
<li><big>A demo reproducing Fig. 2-13 of Ogata (1988) shows how to work with (fully) parametric models. 
</big></li>
</ul>
<br>
<big><span style="font-weight: bold;">Other R packages required to run STAR</span>:<br>
</big>
<div style="margin-left: 40px;"><big>You will have to download from
your favorite <a href="http://cran.r-project.org/mirrors.html">CRAN</a>
server and install the R package <span style="font-family: monospace;">R2HTML</span> of Eric Lecoutre in order to generate reports in html format 
as well package <span style="font-family: monospace;">sound</span> of Matthias Heymann in order to generate genuine spikes songs.
Hidden Markov modeling requires  the installation of the 
<span style="font-family: monospace;">HiddenMarkov</span> package of David Harte. 
</big><br></div>
<br>
<br>
STAR comes with a <a href="STAR_folder/STAR.pdf">full documentation</a> and a couple of demo files as well as the 
<a href="http://www.biomedicale.univ-paris5.fr/physcerv/C_Pouzat/Compendium.html">vignette</a> of the manuscript describing the basic functionalities of the software. <br>
<br>
STAR includes several data sets:
<ul>
<li>Several neurons recorded extracellularly and simultaneously from the Cockroach antennal lobe. These data were recorded
and the spike sorting was performed by <a href="mailto:antoine.chaffiol@univ-paris5.fr">Antoine Chaffiol</a>. 
The threee data sets include both spontaneous activity and odor responses.</li>
<li>Purkinje cells recording from rat cerebellar slices. Data obtained and sorted by Matthieu Delscluse.</li>
<li>The earthquakes data set used by Ogata (1988).</li>
</ul> <br>
<br>
STAR is under active development any comments, suggestions and
contributions are warmly welcomed.<br>

<p> The <strong>project summary page</strong> you can find <a href="http://<?php echo $domain; ?>/projects/<?php echo $group_name; ?>/"><strong>here</strong></a>. </p>

</body>
</html>
